"""Generate lua/user/pinyin_initials.lua from pypinyin.

Run with: uvx --from pypinyin python scripts/gen_pinyin_initials.py
"""

from pathlib import Path

from pypinyin import Style, pinyin

FIRST, LAST = 0x4E00, 0x9FFF
out = Path(__file__).resolve().parent.parent / "lua" / "user" / "pinyin_initials.lua"

entries = []
multi = 0
for cp in range(FIRST, LAST + 1):
    readings = pinyin(chr(cp), style=Style.FIRST_LETTER, heteronym=True, errors=lambda _: None)
    initials = "".join(sorted({r[0] for r in (readings[0] if readings else []) if r and r[0].isalpha()}))
    multi += len(initials) > 1
    entries.append(initials)

out.write_text(
    "\n".join(
        [
            "-- Generated by scripts/gen_pinyin_initials.py. Do not edit.",
            "-- Possible pinyin initials for each code point from U+4E00 to U+9FFF,",
            "-- separated by '|'. An empty entry means the character has no reading.",
            "return {",
            f"  first = {FIRST:#x},",
            f'  data = "{"|".join(entries)}",',
            "}",
            "",
        ]
    ),
    encoding="utf-8",
)
print(f"wrote {out}: {len(entries)} code points, {multi} with several initials")
